- name: run on local
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Run terraform
      terraform:
        project_path: "./tf"
        force_init: yes
        state: present
      register: trfrm

    - name: Add instance host
      add_host:
        name: my_java_app_server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.instance_ip_addr.value }}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        
- name: Timeout for instance creating
  hosts: 127.0.0.1
  connection: local     
  
  tasks:
    - name: Wait for a ssh port become available
      wait_for:
        host: "{{ trfrm.outputs.instance_ip_addr.value }}"
        port: 22
      
- name: Deploy app
  hosts: my_java_app_server
  tasks:
    - block:   
      - name: Update apt cache and install jdk17
        apt:
          update_cache: yes
          name: openjdk-17-jdk-headless
          state: present
        become: yes

      - name: Copy artifacts
        copy:
          src: "{{ jar_path }}"
          dest: /home/ubuntu/target
        
      - name: Configure Java app service
        copy: 
          src: "{{ service_path }}"
          dest: /etc/systemd/system
          mode: '0777'
        become: yes
    
      - name: Start Java app service
        systemd:
          daemon_reload: true
          name: my_java_app
          state: restarted
        become: yes
     
      rescue:
       - name: Clean up resources because of an error
         terraform:
           project_path: "./tf"
           state: absent 
         delegate_to: 127.0.0.1
